# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narwhals', '0005_auto_20160308_1941'),
    ]

    operations = [

        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),

        migrations.AlterField(
            model_name='workout',
            name='sport',
            field=models.IntegerField(choices=[(0, b'swimming'), (1, b'cycling'), (2, b'hiking')], default=0),
        ),

        migrations.RunSQL(migrations.RunSQL.noop,
                          reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
