# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170128_2346'),
        ('narwhals', '0006_auto_20161104_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunWorkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('dateStart', models.DateTimeField(blank=True, help_text='Date of the creation', null=True, verbose_name='Creation date')),
                ('dateFinish', models.DateTimeField(blank=True, help_text='End date', null=True, verbose_name='End date')),
                ('difficulty', models.IntegerField(blank=True, default=1, help_text='Difficulty of the training', null=True, verbose_name='Difficulty of the training')),
                ('mood', models.IntegerField(blank=True, default=1, help_text="User's mood", null=True, verbose_name="User's mood")),
                ('duration', models.IntegerField(blank=True, help_text='Duration of the training', null=True, verbose_name='Duration of the training')),
                ('distance', models.FloatField(blank=True, help_text='Distance of the training', null=True, verbose_name='Distance of the training')),
                ('ascendedMeters', models.IntegerField(blank=True, help_text='Ascended meters', null=True, verbose_name='Acended meters')),
                ('descendedMeters', models.IntegerField(blank=True, help_text='Descended meters', null=True, verbose_name='Descended meters')),
                ('maxAltitude', models.IntegerField(blank=True, help_text='Maximum altitude', null=True, verbose_name='Maximum altitude')),
                ('minAltitude', models.IntegerField(blank=True, help_text='Minimum altitude', null=True, verbose_name='Minimum altitude')),
                ('speed', models.FloatField(blank=True, help_text='Speed in meter/seconds', null=True, verbose_name='Speed in meter/seconds')),
                ('maxSpeed', models.FloatField(blank=True, help_text='Max speed in meter/seconds', null=True, verbose_name='Max speed in meter/seconds')),
                ('file_log', models.FileField(blank=True, help_text="Workout's file training data", null=True, upload_to=b'uploads/running/%Y/%m/%d/', verbose_name="Workout's file training data")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.Runner')),
            ],
        ),
        migrations.CreateModel(
            name='SwimWorkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('dateStart', models.DateTimeField(blank=True, help_text='Date of the creation', null=True, verbose_name='Creation date')),
                ('dateFinish', models.DateTimeField(blank=True, help_text='End date', null=True, verbose_name='End date')),
                ('difficulty', models.IntegerField(blank=True, default=1, help_text='Difficulty of the training', null=True, verbose_name='Difficulty of the training')),
                ('mood', models.IntegerField(blank=True, default=1, help_text="User's mood", null=True, verbose_name="User's mood")),
                ('duration', models.IntegerField(blank=True, help_text='Duration of the training', null=True, verbose_name='Duration of the training')),
                ('distance', models.FloatField(blank=True, help_text='Distance of the training', null=True, verbose_name='Distance of the training')),
                ('strokes', models.FloatField(blank=True, help_text='Calculated strokes', null=True, verbose_name='Calculated strokes')),
                ('speedAverage', models.FloatField(blank=True, help_text='Average speed in meter/seconds', null=True, verbose_name='Average speed in meter/seconds')),
                ('strokeAverage', models.FloatField(blank=True, help_text='Average strokes per second', null=True, verbose_name='Average strokes per second')),
                ('file_log', models.FileField(blank=True, help_text="Workout's file training data", null=True, upload_to=b'uploads/swimming/%Y/%m/%d/', verbose_name="Workout's file training data")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.Swimmer')),
            ],
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
