# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narwhals', '0007_auto_20170129_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runworkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Runner'),
        ),
        migrations.AlterField(
            model_name='swimworkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Swimmer'),
        ),
    ]
