# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narwhals', '0009_auto_20170413_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runworkout',
            name='distance',
            field=models.FloatField(default=0, help_text='Distance of the training', verbose_name='Distance of the training'),
        ),
        migrations.AlterField(
            model_name='runworkout',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration of the training', verbose_name='Duration of the training'),
        ),
    ]
