# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-28 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='trend',
            field=models.CharField(choices=[(b'up', b'UP'), (b'equals', b'EQUALS'), (b'down', b'DOWN')], default=b'equals', max_length=10),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='trend',
            field=models.CharField(choices=[(b'up', b'UP'), (b'equals', b'EQUALS'), (b'down', b'DOWN')], default=b'equals', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'avatars'),
        ),
    ]
