# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunningStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, help_text='Duration of the training', verbose_name='Duration of the training')),
                ('distance', models.FloatField(default=0, help_text='Distance of the training', verbose_name='Distance of the training')),
            ],
        ),
        migrations.CreateModel(
            name='SwimmingStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, help_text='Duration of the training', verbose_name='Duration of the training')),
                ('distance', models.FloatField(default=0, help_text='Distance of the training', verbose_name='Distance of the training')),
                ('strokes', models.FloatField(default=0, help_text='Calculated strokes', verbose_name='Calculated strokes')),
            ],
        ),
    ]
